sudo: required

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - sed -i -e 's@##LIBKI_VERSION##@'"$TRAVIS_BRANCH"'@g' libki-manual.adoc
  - sed -i -e 's@{libki-version}@'"$TRAVIS_BRANCH"'@g' libki-manual.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output libki-manual.adoc      
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf  asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output libki-manual.adoc    
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-epub asciidoctor/docker-asciidoctor asciidoctor-epub3 -D /documents/output libki-manual.adoc    

after_error: 
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:      
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit 0; fi
  - cd ..
  - git clone https://${GITHUB_TOKEN}@github.com/Libki/manual-libki-org.git
  - ls -alh
  - if [ -d "manual-libki-org/docs/${TRAVIS_BRANCH}" ]; then rm -rf manual-libki-org/docs/${TRAVIS_BRANCH}; fi
  - mkdir -p manual-libki-org/docs/${TRAVIS_BRANCH}
  - cp -r libki-manual/output/. manual-libki-org/docs/${TRAVIS_BRANCH}/.
  - cp -r libki-manual/images manual-libki-org/docs/${TRAVIS_BRANCH}/.
  - cd manual-libki-org
  - ls -alh
  - git config user.name "Kyle M Hall"
  - git config user.email "kyle@bywatersolutions.com"
  - git add docs/${TRAVIS_BRANCH}
  - git status
  - git commit -m "Deploy manual version '${TRAVIS_BRANCH}' to libki.manual.org"
  - git push origin HEAD:master
